### ISSUE TITLE
Wireshark is crashing when clicking "Capture packets"

### ISSUE THREAD

**Issue by parmen789** [vlad9486/tezos-dissector#1]
Cannot capture packets due to following error.

```
thread '<unnamed>' panicked at 'assertion failed: range.contains(&offset.data_offset) ||
    (offset.data_offset == range.end && length == 0)', src/value/message.rs:103:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
Aborted
```

I am using prebuild because I have problems with dependencies on manual build. Prebuild suceeds to run. My system is Ubuntu 20, running as WSL. I have it set up in a way that GUI stuff works right.

**Comment by parmen789** [comment]
This issue was probably caused by me starting wireshark and node in wrong sequence, but I am not sure about it, because I really think I started first wireshark and then node, same as now - now it works. Wouldn't close it yet, in case it was not caused by my mistake.

**Comment by vlad9486** [comment]
Thank you for this report. The problem exist and will be fixed. Could you please specify how often it happens. How bad is it? Is it happened once, or constantly, or some other frequency?

**Comment by vlad9486** [comment]
Please, checkout the new version of the tezos-dissector. We fixed crashes, done refactoring, perform fuzzing. It should fix the issue.
